id: IC50F6DB1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T19:01:53+00:00'
last_modified: '2022-06-08T14:32:52.743771+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25479
  title: སྲོག་ཆགས་འབྲི་ཚུལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    FD65:
      image_group_id: I1KG25481
      title: ''
      total_pages: 202
      order: 1
      base_file: FD65.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
