id: P010567
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25479
  title: སྲོག་ཆགས་འབྲི་ཚུལ།
  author: ''
  volumes:
    564ba3f1dc7a4db9b76bcbe29d536dd4:
      image_group_id: I1KG25481
      title: ''
      volume_number: 1
      total_pages: 202
      base_file: v001.txt
