id: P010567
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-20 10:14:27.375951
source_metadata:
  id: bdr:W1KG25479
  title: སྲོག་ཆགས་འབྲི་ཚུལ།
  author: ''
  volumes:
    564ba3f1dc7a4db9b76bcbe29d536dd4:
      image_group_id: I1KG25481
      title: ''
      volume_number: 1
      total_pages: 202
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
